# Generated by Django 4.2.7 on 2023-11-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='racas',
            fields=[
                ('nomeRaca', models.TextField(primary_key=True, serialize=False)),
                ('atributosRaca', models.TextField(max_length=255)),
                ('habilidadesRaca', models.TextField(max_length=510)),
                ('periciasRaca', models.TextField(max_length=510)),
            ],
        ),
    ]
